### ISSUE TITLE
Backlinks not working

### ISSUE THREAD

**Issue by thomassajot** [theowenyoung/obsidian-template-gatsby-theme-primer-wiki#1]
Hello, thanks for the great theme and support ! 

I am using the obsidian template. I added the support for latex equations (remark-katex), but it seems the backlinks are not working anymore. 
I am new to using JS and I have not found the reason why this is happening.  Would you know what is the issue or point me in the right direction ?
Here is the repo: https://github.com/thomassajot/brain-dam

Example where the backlink / wiki link is not working. And the image display as well.

![Screenshot (10)](https://user-images.githubusercontent.com/15252203/170574656-f3000af3-1187-44b8-a8d8-dc4ec9231422.png)

Thanks for the help !

**Comment by thomassajot** [comment]
As I created this issue, I found out that the website is not working as well in Github pages, but I am able to run it locally. Any other ideas of why this could be the case ?

**Comment by thomassajot** [comment]
Hello, with enough fiddlign around, I seemed to have resolved this issue.

**Comment by dsimonow** [comment]
what did you do to achieve resolving it?
